language: python
python: 3.8

services:
  - postgresql

env:
  global:
    - CC_TEST_REPORTER_ID=651fcc97eae2b0dff73bf2106e578a378193ab1aa30a49dd29bd389a537b9b28
    - SECRET_KEY=abc123

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install: make

before_install:
  - pip3 install poetry
  - psql -c 'create database travis_ci_test;' -U postgres

install:
  - make install

script:
  - make migrate
  - make lint
  - make coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false