# Generated by Django 3.0.5 on 2020-04-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name_plural': 'Task Statuses'},
        ),
    ]
